import 'package:flutter/material.dart';

/// Location Data for Provinces, Districts, and Municipalities
const Map<String, Map<String, List<String>>> locationData = {
  'Province 1': {
    'Bhojpur': ['Bhojpur Municipality', 'Shadananda Municipality'],
    'Morang': ['Biratnagar', 'Urlabari', 'Rangeli'],
    'Sunsari': ['Itahari', 'Dharan', 'Inaruwa'],
    'Dhankuta': ['Dhankuta Municipality'],
    'Panchthar': ['Phidim Municipality'],
    'Ilam': ['Ilam Municipality', 'Suryodaya Municipality'],
    'Jhapa': ['Birtamode', 'Mechinagar', 'Damak'],
    'Sankhuwasabha': ['Khandbari Municipality'],
    'Tehrathum': ['Myanglung Municipality'],
    'Udayapur': ['Gaighat Municipality', 'Katari Municipality'],
    'Okhaldhunga': ['Okhaldhunga Municipality'],
    'Khotang': ['Diktel Municipality'],
    'Solukhumbu': ['Salleri Municipality'],
    'Taplejung': ['Phungling Municipality'],
  },
  'Madhesh Pradesh': {
    'Saptari': ['Rajbiraj Municipality', 'Kanchanrup Municipality'],
    'Siraha': ['Lahan Municipality', 'Siraha Municipality'],
    'Dhanusha': ['Janakpur', 'Mithila Municipality'],
    'Mahottari': ['Jaleshwar Municipality', 'Bardibas Municipality'],
    'Sarlahi': ['Malangwa Municipality', 'Haripur Municipality'],
    'Bara': ['Kalaiya Municipality', 'Simraungadh Municipality'],
    'Parsa': ['Birgunj', 'Pokhariya Municipality'],
    'Rautahat': ['Gaur Municipality', 'Garuda Municipality'],
  },
  'Bagmati': {
    'Kathmandu': ['Kathmandu', 'Kirtipur', 'Tokha'],
    'Lalitpur': ['Lalitpur', 'Godawari', 'Mahalaxmi Municipality'],
    'Bhaktapur': ['Bhaktapur', 'Madhyapur Thimi', 'Changunarayan'],
    'Makwanpur': ['Hetauda', 'Thaha Municipality'],
    'Chitwan': ['Bharatpur', 'Ratnanagar', 'Khairahani'],
    'Kavrepalanchok': ['Banepa', 'Dhulikhel', 'Panauti'],
    'Sindhuli': ['Kamalamai Municipality'],
    'Ramechhap': ['Manthali Municipality'],
    'Dolakha': ['Bhimeshwar Municipality'],
    'Sindhupalchok': ['Chautara Sangachokgadhi Municipality'],
    'Nuwakot': ['Bidur Municipality'],
    'Rasuwa': ['Uttargaya Rural Municipality'],
  },
  'Gandaki': {
    'Kaski': ['Pokhara', 'Lekhnath'],
    'Lamjung': ['Besisahar Municipality'],
    'Tanahun': ['Damauli Municipality'],
    'Syangja': ['Waling Municipality'],
    'Gorkha': ['Gorkha Municipality'],
    'Baglung': ['Baglung Municipality'],
    'Myagdi': ['Beni Municipality'],
    'Parbat': ['Kushma Municipality'],
    'Manang': ['Chame Rural Municipality'],
    'Mustang': ['Jomsom Rural Municipality'],
  },
  'Lumbini': {
    'Dang': ['Ghorahi', 'Tulsipur', 'Lamahi'],
    'Banke': ['Nepalgunj', 'Kohalpur'],
    'Rupandehi': ['Butwal', 'Siddharthanagar', 'Tilottama'],
    'Kapilvastu': ['Taulihawa Municipality'],
    'Palpa': ['Tansen Municipality'],
    'Gulmi': ['Tamghas Municipality'],
    'Arghakhanchi': ['Sandhikharka Municipality'],
    'Bardiya': ['Gulariya Municipality'],
    'Parasi': ['Ramgram Municipality'],
    'Rolpa': ['Liwang Municipality'],
    'Pyuthan': ['Pyuthan Municipality'],
  },
  'Karnali': {
    'Surkhet': ['Birendranagar Municipality'],
    'Dailekh': ['Narayan Municipality'],
    'Jajarkot': ['Khalanga Municipality'],
    'Salyan': ['Sharada Municipality'],
    'Rukum West': ['Musikot Municipality'],
    'Rukum East': ['Putha Uttarganga'],
    'Dolpa': ['Dunai Municipality'],
    'Humla': ['Simikot Rural Municipality'],
    'Mugu': ['Gamgadhi Municipality'],
    'Jumla': ['Chandannath Municipality'],
    'Kalikot': ['Manma Municipality'],
  },
  'Sudurpashchim': {
    'Kailali': ['Dhangadhi', 'Tikapur Municipality'],
    'Kanchanpur': ['Mahendranagar Municipality'],
    'Dadeldhura': ['Amargadhi Municipality'],
    'Doti': ['Dipayal Silgadhi Municipality'],
    'Baitadi': ['Dasharathchand Municipality'],
    'Bajhang': ['Chainpur Municipality'],
    'Bajura': ['Martadi Municipality'],
    'Achham': ['Mangalsen Municipality'],
    'Darchula': ['Darchula Municipality'],
  },
};
